### ISSUE TITLE
Class is not key value compliant

### ISSUE THREAD

**Issue by elementhk** [abdullahselek/DragDropUI#3]
Hi, I imported manually DragDropUI in my Xcode project and set the UICollectionViewCell class to DDCollectionViewCell. But app is crashing on starting.

Essen.DDCollectionViewCell 0x7f9a0f68ec80> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key dateView.'

**Comment by abdullahselek** [comment]
Hi, your custom collection view cell should extend from DDCollectionViewCell. Like
```
import UIKit

class MyCollectionViewCell: DDCollectionViewCell  {

}
```

**Comment by elementhk** [comment]
Hi, It's still giving the same error, 
DDCollectionViewCell 0x7fe8258d9460> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key playerView.'

I have set the class of individual UICollectionViewCells to DDCollectionViewCell
![screen shot 2017-08-21 at 11 54 19](https://user-images.githubusercontent.com/20043304/29514081-8885cf0a-8667-11e7-9b29-0f67f9ea2c74.png)
![screen shot 2017-08-21 at 11 54 31](https://user-images.githubusercontent.com/20043304/29514080-887db8a6-8667-11e7-8ef5-1d9b7cf635d5.png)

![screen shot 2017-08-21 at 12 38 19](https://user-images.githubusercontent.com/20043304/29515676-a5bb0710-866d-11e7-948f-2851091d36d9.png)

**Comment by abdullahselek** [comment]
Hi @HumayunKaleem you have to set the class to DashboardCollectionViewCell not to DDCollectionViewCell. And your DashboardCollectionViewCell seems correct.

**Comment by elementhk** [comment]
Hi, Thanks for replying back @abdullahselek. App is crashing on DDGestureRecognizer.
![screen shot 2017-08-21 at 13 22 47](https://user-images.githubusercontent.com/20043304/29517128-dbb88a30-8673-11e7-8213-02705d5ff1b5.png)

Edit: I want to move the Header Section of CollectionView. Is it possible with this library?

**Comment by abdullahselek** [comment]
I think the last changes should fix this crash. It might possible but the way you follow seems wrong.

**Comment by elementhk** [comment]
The CollectionViewCells are still not moving just that app is not crashing anymore. Can you give a hint. I have a CollectionReusableView with a Label. I want to move it's section header? Do i need to use CollectionViewCell.

**Comment by abdullahselek** [comment]
For now there is no draggable separate class for UICollectionReusableView inside the DragDropUI. You already added source files inside your project, try to create your own UICollectionReusableView which extends from DDProtocol.

Like

```
class MyCollectionReusableView: UICollectionReusableView, DDProtocol  {

    ...

    override public func didMoveToSuperview() {
        if self.superview != nil {
            self.isUserInteractionEnabled = true
            self.registerGesture()
        } else {
            self.removeGesture()
        }
    }
}
```

I suggest you to be careful after implementing it dragging these type of components might be tricky.

**Comment by elementhk** [comment]
Hi, Yeah thanks for the input. I will work on it and let's see if i am able to do it or not.
